# Site settings
title:
email: saurabhbaliyan000@gmail.com
author:
description:
url:

# plugins
plugins: [jekyll-paginate]
paginate: 3

# Build settings
permalink: :title/
sass:
  sass_dir: css

# Social icons
show_social_icons: true
github_username: hbaruas
linkedin_username: saurabh-kumar-b10285b6